import type { CurrencyCode, CurrencyConfig, StudioDefaults, StudioProfile } from '../types/studio';
import type { EquipmentItem, GlassItem } from '../types/project';

export const LOGO_URL = `${import.meta.env.BASE_URL}favicon.svg`;

export const CURRENCIES: Record<CurrencyCode, CurrencyConfig> = {
  TRY: {
    code: 'TRY',
    symbol: '₺',
    name: 'Türk Lirası (₺)',
    decimalDigits: 2,
    position: 'after',
  },
  USD: {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar ($)',
    decimalDigits: 2,
    position: 'before',
  },
  EUR: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro (€)',
    decimalDigits: 2,
    position: 'before',
  },
  GBP: {
    code: 'GBP',
    symbol: '£',
    name: 'British Pound (£)',
    decimalDigits: 2,
    position: 'before',
  },
  CAD: {
    code: 'CAD',
    symbol: 'CA$',
    name: 'Canadian Dollar (CA$)',
    decimalDigits: 2,
    position: 'before',
  },
  AUD: {
    code: 'AUD',
    symbol: 'A$',
    name: 'Australian Dollar (A$)',
    decimalDigits: 2,
    position: 'before',
  },
  CHF: {
    code: 'CHF',
    symbol: 'CHF',
    name: 'Swiss Franc (CHF)',
    decimalDigits: 2,
    position: 'before',
  },
};

export const INITIAL_EQUIPMENT_LIST: EquipmentItem[] = [
  {
    id: 'eq-grinder',
    name: 'Cam Taşlama Makinesi (Grinder 2000S)',
    category: 'machine',
    purchasePrice: 6500,
    lifespanHours: 2500,
    isElectrical: true,
    powerWatts: 150,
    usageHours: 1.5,
    enabled: true,
  },
  {
    id: 'eq-soldering-iron',
    name: 'Vitray Havyası (Hakko FX-601 / 100W)',
    category: 'machine',
    purchasePrice: 3200,
    lifespanHours: 2000,
    isElectrical: true,
    powerWatts: 100,
    usageHours: 2.0,
    enabled: true,
  },
  {
    id: 'eq-cutter',
    name: 'Elmas Cam Kesici (Toyo TC-17)',
    category: 'tool',
    purchasePrice: 1200,
    lifespanHours: 1000,
    isElectrical: false,
    powerWatts: 0,
    usageHours: 1.0,
    enabled: true,
  },
  {
    id: 'eq-pliers',
    name: 'Kırıcı & Koşucu Pens Takımı',
    category: 'tool',
    purchasePrice: 1100,
    lifespanHours: 3500,
    isElectrical: false,
    powerWatts: 0,
    usageHours: 0.8,
    enabled: true,
  },
  {
    id: 'eq-grinder-bit',
    name: 'Elmas Taşlama Ucu (3/4" Standart Grit)',
    category: 'consumable_tool',
    purchasePrice: 750,
    lifespanHours: 300,
    isElectrical: false,
    powerWatts: 0,
    usageHours: 1.5,
    enabled: true,
  },
  {
    id: 'eq-lightpad',
    name: 'Işıklı Tasarım & Montaj Masası (A3 LED)',
    category: 'machine',
    purchasePrice: 1400,
    lifespanHours: 5000,
    isElectrical: true,
    powerWatts: 24,
    usageHours: 4.0,
    enabled: true,
  },
  {
    id: 'eq-fume-extractor',
    name: 'Duman Emici & Karbon Filtre',
    category: 'safety',
    purchasePrice: 1800,
    lifespanHours: 3000,
    isElectrical: true,
    powerWatts: 40,
    usageHours: 2.0,
    enabled: true,
  },
];

export const INITIAL_STUDIO_PROFILE: StudioProfile = {
  studioName: 'Vitralis Cam Vitray Atölyesi',
  artisanName: 'Vitray Sanatçısı',
  phone: '+90 (555) 000 00 00',
  email: 'info@vitralis-studio.com',
  website: 'https://vitralis.art',
  address: 'Sanatçılar Çarşısı No:12, Kadıköy / İstanbul',
  taxNumber: '1234567890',
  quoteHeaderNotes: 'Özel tasarım el yapımı Tiffany cam vitray eseri için hazırlanmış resmi atölye fiyat teklifidir.',
  quoteTermsConditions: '• Teklif 30 gün süreyle geçerlidir.\n• Sipariş onayı ile %40 kapora tahsil edilir.\n• Tüm cam parçaları el kesimi ve orijinal vitray camıdır (Spectrum, Wissmach, Oceanside).',
  careInstructions: '• Eseri sadece kuru veya hafif nemli mikrofiber bezle nazikçe siliniz.\n• Amonyaklı veya aşındırıcı kimyasal temizleyiciler kullanmayınız.\n• Lehim hatlarının parlaklığını korumak için yılda bir kez karnauba vitray cilası uygulayabilirsiniz.',
};

export const INITIAL_STUDIO_DEFAULTS: StudioDefaults = {
  currency: 'TRY',
  language: 'tr',
  theme: 'dark',
  hourlyRate: 350,
  electricityKwhRate: 3.40,
  defaultWasteRiskPercentage: 12,
  defaultProfitMarginPercentage: 45,
  defaultVatPercentage: 20,
  defaultFoilPrice: 280,
  defaultFoilLengthMeters: 33,
  defaultSolderPrice: 850,
  defaultSolderSpoolGrams: 500,
  defaultZincCamePricePerMeter: 90,
  defaultHangingHookPrice: 25,
  defaultChainPricePerMeter: 45,
  defaultFluxCost: 35,
  defaultPatinaCost: 45,
  defaultPolishCost: 30,
  defaultEquipment: INITIAL_EQUIPMENT_LIST,
};

export const SAMPLE_GLASS_ITEMS: GlassItem[] = [
  {
    id: 'glass-1',
    name: 'Opal Beyaz & Amber Dalgalı Cam',
    type: 'Spectrum Opal',
    color: 'Amber & Beyaz',
    colorHex: '#f59e0b',
    shape: 'rect',
    widthCm: 25,
    heightCm: 20,
    diameterCm: 0,
    customAreaSqCm: 500,
    quantity: 1,
    unitPrice: 2800,
    priceUnit: 'sqm',
    calculatedAreaSqM: 0.05,
    calculatedCost: 140,
    notes: 'Ana gövde ve taç yapraklar için',
  },
  {
    id: 'glass-2',
    name: 'Kobalt Mavi Su Dalgası (Waterglass)',
    type: 'Spectrum Waterglass',
    color: 'Kobalt Mavi',
    colorHex: '#2563eb',
    shape: 'rect',
    widthCm: 30,
    heightCm: 25,
    diameterCm: 0,
    customAreaSqCm: 750,
    quantity: 1,
    unitPrice: 3200,
    priceUnit: 'sqm',
    calculatedAreaSqM: 0.075,
    calculatedCost: 240,
    notes: 'Arka plan derinlik paneli',
  },
  {
    id: 'glass-3',
    name: 'Zümrüt Yeşil Katedral Cam',
    type: 'Wissmach Cathedral',
    color: 'Zümrüt Yeşili',
    colorHex: '#059669',
    shape: 'circle',
    widthCm: 0,
    heightCm: 0,
    diameterCm: 18,
    customAreaSqCm: 254.47,
    quantity: 2,
    unitPrice: 2600,
    priceUnit: 'sqm',
    calculatedAreaSqM: 0.0509,
    calculatedCost: 132.34,
    notes: 'Yaprak ve bordür madalyonları',
  },
];

export const EMPTY_COST_BREAKDOWN = {
  totalGlassAreaSqM: 0,
  totalGlassCost: 0,
  foilCost: 0,
  solderCost: 0,
  chemicalsCost: 0,
  reinforcementCost: 0,
  customConsumablesCost: 0,
  totalConsumablesCost: 0,
  totalLaborHours: 0,
  totalLaborCost: 0,
  totalEquipmentDepreciationCost: 0,
  totalElectricityKwh: 0,
  totalElectricityCost: 0,
  rawBaseCost: 0,
  wasteAmount: 0,
  costWithWaste: 0,
  profitAmount: 0,
  subtotalSellingPrice: 0,
  discountAmount: 0,
  priceAfterDiscount: 0,
  taxAmount: 0,
  finalSellingPrice: 0,
  grossMarginPercentage: 0,
  profitRatio: 0,
  materialCostRatio: 0,
  laborCostRatio: 0,
  overheadCostRatio: 0,
  costPerGlassPiece: 0,
  costPerSqM: 0,
  effectiveHourlyYield: 0,
};

