import type { VitralisProject } from '../types/project';
import { INITIAL_EQUIPMENT_LIST } from './defaults';

export interface ProjectTemplate {
  id: string;
  nameTr: string;
  nameEn: string;
  descriptionTr: string;
  descriptionEn: string;
  category: 'suncatcher' | 'lamp' | 'panel' | 'terrarium' | 'mirror';
  badge: string;
  iconName: string;
  templateData: VitralisProject;
}

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'template-suncatcher',
    nameTr: 'Tiffany Güneş Kapanı (Suncatcher)',
    nameEn: 'Tiffany Suncatcher (Hanging Ornament)',
    descriptionTr: 'Orta boy (25x30cm), 18 parçalı renkli Tiffany vitray asma dekor.',
    descriptionEn: 'Medium-sized (25x30cm), 18-piece colorful Tiffany hanging decor with chain.',
    category: 'suncatcher',
    badge: '18 Parça / ~5 Saat',
    iconName: 'Sun',
    templateData: {
      metadata: {
        id: 'template-suncatcher-data',
        title: 'Monarch Kelebek & Çiçek Güneş Kapanı',
        clientName: 'Örnek Müşteri',
        projectType: 'tiffany',
        dimensions: { widthCm: 25, heightCm: 30 },
        pieceCount: 18,
        difficulty: 'intermediate',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        status: 'draft',
        notes: 'Bakır folyo tekniği, siyah patina kaplama ve pirinç halkalı montaj.',
      },
      glassItems: [
        {
          id: 'g-1',
          name: 'Amber Sarı Spectrum Opal',
          type: 'Spectrum Opal',
          color: 'Amber Sarı',
          colorHex: '#f59e0b',
          shape: 'rect',
          widthCm: 20,
          heightCm: 15,
          diameterCm: 0,
          customAreaSqCm: 300,
          quantity: 1,
          unitPrice: 2800,
          priceUnit: 'sqm',
          calculatedAreaSqM: 0.03,
          calculatedCost: 84,
          notes: 'Kelebek kanatları',
        },
        {
          id: 'g-2',
          name: 'Kobalt Mavi Wissmach Katedral',
          type: 'Wissmach Cathedral',
          color: 'Kobalt Mavi',
          colorHex: '#2563eb',
          shape: 'rect',
          widthCm: 15,
          heightCm: 15,
          diameterCm: 0,
          customAreaSqCm: 225,
          quantity: 1,
          unitPrice: 2600,
          priceUnit: 'sqm',
          calculatedAreaSqM: 0.0225,
          calculatedCost: 58.5,
          notes: 'Dış çerçeve dalgaları',
        },
        {
          id: 'g-3',
          name: 'Opak Siyah Çizgili Cam',
          type: 'Oceanside Black',
          color: 'Siyah',
          colorHex: '#18181b',
          shape: 'rect',
          widthCm: 10,
          heightCm: 10,
          diameterCm: 0,
          customAreaSqCm: 100,
          quantity: 1,
          unitPrice: 3100,
          priceUnit: 'sqm',
          calculatedAreaSqM: 0.01,
          calculatedCost: 31,
          notes: 'Gövde ve damarlar',
        },
      ],
      consumables: {
        foil: {
          enabled: true,
          foilType: 'Black Backed',
          foilWidth: '7/32" (5.5mm)',
          lengthMeters: 6.5,
          rollPrice: 280,
          rollLengthMeters: 33,
        },
        solder: {
          enabled: true,
          solderRatio: '60/40',
          weightGrams: 140,
          spoolPrice: 850,
          spoolWeightGrams: 500,
        },
        chemicals: {
          fluxCost: 20,
          patinaType: 'black',
          patinaCost: 30,
          finishingPolishCost: 20,
          cleaningSolventCost: 15,
        },
        reinforcement: {
          zincCameMeters: 0,
          zincCamePricePerMeter: 90,
          brassRodsCost: 0,
          hangingHooksCount: 2,
          hangingHookPrice: 20,
          chainMeters: 0.5,
          chainPricePerMeter: 45,
        },
        customConsumables: [],
      },
      labor: {
        hourlyRate: 350,
        stages: [
          { id: 'design', name: 'Tasarım & Şablon Çıkarma', hours: 0.75 },
          { id: 'cutting', name: 'Cam Kesme & Kırma', hours: 1.25 },
          { id: 'grinding', name: 'Kenar Taşlama & Alıştırma', hours: 1.0 },
          { id: 'foiling', name: 'Bakır Folyolama', hours: 0.8 },
          { id: 'soldering', name: 'Lehimleme & Halka Montajı', hours: 1.2 },
          { id: 'finishing', name: 'Siyah Patina, Yıkama & Cila', hours: 0.6 },
          { id: 'packaging', name: 'Özel Koruyucu Paketleme', hours: 0.3 },
        ],
      },
      equipment: INITIAL_EQUIPMENT_LIST.map(e => ({
        ...e,
        usageHours: e.id === 'eq-grinder' ? 1.0 : e.id === 'eq-soldering-iron' ? 1.2 : 0.8,
      })),
      electricity: {
        unitRatePerKwh: 3.4,
        customElectricalEquipment: [],
      },
      marginRisk: {
        wasteRiskPercentage: 10,
        wasteCalculationMode: 'glass_and_consumables',
        targetProfitMarginPercentage: 45,
        vatTaxPercentage: 20,
        discountPercentage: 0,
      },
      breakdown: {} as any,
    },
  },
  {
    id: 'template-lamp',
    nameTr: '16" Tiffany Abajur Şapkası',
    nameEn: '16" Tiffany Lamp Shade',
    descriptionTr: 'Gelişmiş seviye, 240 parça kavisli kalıpta Tiffany cam abajur.',
    descriptionEn: 'Advanced level, 240-piece curved mold floral Tiffany lamp shade.',
    category: 'lamp',
    badge: '240 Parça / ~32 Saat',
    iconName: 'Lamp',
    templateData: {
      metadata: {
        id: 'template-lamp-data',
        title: '16 İnç Wisteria / Mor Çiçekli Tiffany Abajur',
        clientName: 'Atölye Koleksiyonu',
        projectType: 'tiffany',
        dimensions: { widthCm: 40, heightCm: 26, depthCm: 40 },
        pieceCount: 240,
        difficulty: 'masterpiece',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        status: 'draft',
        notes: 'Styrofoam 16" küresel kalıp üzerinde folyolama ve pirinç ring montajı.',
      },
      glassItems: [
        {
          id: 'gl-1',
          name: 'Mor & Eflatun Mermer Dokulu Cam',
          type: 'Spectrum Baroque',
          color: 'Mor Eflatun',
          colorHex: '#9333ea',
          shape: 'rect',
          widthCm: 40,
          heightCm: 30,
          diameterCm: 0,
          customAreaSqCm: 1200,
          quantity: 1,
          unitPrice: 3800,
          priceUnit: 'sqm',
          calculatedAreaSqM: 0.12,
          calculatedCost: 456,
        },
        {
          id: 'gl-2',
          name: 'Zümrüt & Zeytin Yeşili Wissmach',
          type: 'Wissmach Granite',
          color: 'Zeytin Yeşili',
          colorHex: '#15803d',
          shape: 'rect',
          widthCm: 35,
          heightCm: 30,
          diameterCm: 0,
          customAreaSqCm: 1050,
          quantity: 1,
          unitPrice: 3400,
          priceUnit: 'sqm',
          calculatedAreaSqM: 0.105,
          calculatedCost: 357,
        },
        {
          id: 'gl-3',
          name: 'Krem & Karamel Opal Fon Camı',
          type: 'Oceanside Opal',
          color: 'Krem Karamel',
          colorHex: '#fef3c7',
          shape: 'rect',
          widthCm: 50,
          heightCm: 35,
          diameterCm: 0,
          customAreaSqCm: 1750,
          quantity: 1,
          unitPrice: 3100,
          priceUnit: 'sqm',
          calculatedAreaSqM: 0.175,
          calculatedCost: 542.5,
        },
      ],
      consumables: {
        foil: {
          enabled: true,
          foilType: 'Black Backed',
          foilWidth: '7/32" (5.5mm)',
          lengthMeters: 48,
          rollPrice: 280,
          rollLengthMeters: 33,
        },
        solder: {
          enabled: true,
          solderRatio: '60/40',
          weightGrams: 950,
          spoolPrice: 850,
          spoolWeightGrams: 500,
        },
        chemicals: {
          fluxCost: 80,
          patinaType: 'black',
          patinaCost: 95,
          finishingPolishCost: 65,
          cleaningSolventCost: 40,
        },
        reinforcement: {
          zincCameMeters: 1.3,
          zincCamePricePerMeter: 90,
          brassRodsCost: 150,
          hangingHooksCount: 0,
          hangingHookPrice: 0,
          chainMeters: 0,
          chainPricePerMeter: 0,
        },
        customConsumables: [
          { id: 'c-1', name: 'Pirinç Üst Tepe Yüzüğü (Brass Lamp Ring 3")', quantity: 1, unitCost: 180, unit: 'pcs' },
          { id: 'c-2', name: 'Kalıp Aşınma Payı (Styrofoam Mold Share)', quantity: 1, unitCost: 120, unit: 'pcs' },
        ],
      },
      labor: {
        hourlyRate: 350,
        stages: [
          { id: 'design', name: 'Tasarım & Kalıp Şablon Hazırlığı', hours: 3.5 },
          { id: 'cutting', name: '240 Parça Cam Kesme & Numaralama', hours: 7.5 },
          { id: 'grinding', name: 'Hassas Kenar Taşlama & Alıştırma', hours: 6.0 },
          { id: 'foiling', name: 'Bakır Folyolama (Tüm Parçalar)', hours: 5.5 },
          { id: 'soldering', name: 'Kalıp Üzeri Montaj & Çift Yüz Lehim', hours: 7.0 },
          { id: 'finishing', name: 'Patinaj, Yıkama, Tel Takviye & Cila', hours: 2.5 },
          { id: 'packaging', name: 'Özel Sandıklama & Paketleme', hours: 1.0 },
        ],
      },
      equipment: INITIAL_EQUIPMENT_LIST.map(e => ({
        ...e,
        usageHours: e.id === 'eq-grinder' ? 6.0 : e.id === 'eq-soldering-iron' ? 7.0 : 4.0,
      })),
      electricity: {
        unitRatePerKwh: 3.4,
        customElectricalEquipment: [],
      },
      marginRisk: {
        wasteRiskPercentage: 15,
        wasteCalculationMode: 'glass_and_consumables',
        targetProfitMarginPercentage: 55,
        vatTaxPercentage: 20,
        discountPercentage: 0,
      },
      breakdown: {} as any,
    },
  },
  {
    id: 'template-leadcame-window',
    nameTr: 'Kurşunlu Vitray Pencere (60x90cm)',
    nameEn: 'Lead Came Stained Glass Window (60x90cm)',
    descriptionTr: 'Klasik H-profil kurşun çıtalı ve macunlu mimari vitray paneli.',
    descriptionEn: 'Traditional H-profile lead came architectural stained glass window with cement.',
    category: 'panel',
    badge: '42 Parça / ~16 Saat',
    iconName: 'LayoutGrid',
    templateData: {
      metadata: {
        id: 'template-window-data',
        title: 'Geometrik Kurşunlu Vitray Kapı Üstü Pencere',
        clientName: 'Villa Restorasyon Projesi',
        projectType: 'lead_came',
        dimensions: { widthCm: 60, heightCm: 90 },
        pieceCount: 42,
        difficulty: 'expert',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        status: 'draft',
        notes: '6mm Kurşun H-profil, çinko dış çerçeve, vitray çimentosu ile su sızdırmazlık.',
      },
      glassItems: [
        {
          id: 'gw-1',
          name: 'Antik Şeffaf Dokulu Cam (Restoration Glass)',
          type: 'Lambert Antique Clear',
          color: 'Şeffaf Dokulu',
          colorHex: '#e2e8f0',
          shape: 'rect',
          widthCm: 55,
          heightCm: 45,
          diameterCm: 0,
          customAreaSqCm: 2475,
          quantity: 1,
          unitPrice: 2400,
          priceUnit: 'sqm',
          calculatedAreaSqM: 0.2475,
          calculatedCost: 594,
        },
        {
          id: 'gw-2',
          name: 'Amber & Kırmızı Katedral Cam Bordür',
          type: 'Wissmach Cathedral',
          color: 'Amber & Yakut',
          colorHex: '#b91c1c',
          shape: 'rect',
          widthCm: 55,
          heightCm: 35,
          diameterCm: 0,
          customAreaSqCm: 1925,
          quantity: 1,
          unitPrice: 3200,
          priceUnit: 'sqm',
          calculatedAreaSqM: 0.1925,
          calculatedCost: 616,
        },
        {
          id: 'gw-3',
          name: 'Kobalt Mavi Orta Madalyon',
          type: 'Spectrum Opal',
          color: 'Kobalt Mavi',
          colorHex: '#1d4ed8',
          shape: 'circle',
          widthCm: 0,
          heightCm: 0,
          diameterCm: 25,
          customAreaSqCm: 490.87,
          quantity: 1,
          unitPrice: 3600,
          priceUnit: 'sqm',
          calculatedAreaSqM: 0.049,
          calculatedCost: 176.4,
        },
      ],
      consumables: {
        foil: {
          enabled: false,
          foilType: 'None (Lead Came Used)',
          foilWidth: 'None',
          lengthMeters: 0,
          rollPrice: 280,
          rollLengthMeters: 33,
        },
        solder: {
          enabled: true,
          solderRatio: '50/50',
          weightGrams: 350,
          spoolPrice: 750,
          spoolWeightGrams: 500,
        },
        chemicals: {
          fluxCost: 40,
          patinaType: 'black',
          patinaCost: 60,
          finishingPolishCost: 50,
          cleaningSolventCost: 40,
        },
        reinforcement: {
          zincCameMeters: 3.0,
          zincCamePricePerMeter: 90,
          brassRodsCost: 120,
          hangingHooksCount: 0,
          hangingHookPrice: 0,
          chainMeters: 0,
          chainPricePerMeter: 0,
        },
        customConsumables: [
          { id: 'lc-1', name: 'Kurşun Profil (H-Came 6mm)', quantity: 14, unitCost: 45, unit: 'meters' },
          { id: 'lc-2', name: 'Vitray Macunu & Tebeşir Tozu (Glazing Cement)', quantity: 1, unitCost: 110, unit: 'set' },
        ],
      },
      labor: {
        hourlyRate: 350,
        stages: [
          { id: 'design', name: '1:1 Karton Şablon & Kurşun Payı Çizimi', hours: 2.5 },
          { id: 'cutting', name: 'Çift Bıçaklı Makas ile Şablon & Cam Kesimi', hours: 4.0 },
          { id: 'grinding', name: 'Kurşun Yatağına Göre Kenar Düzeltme', hours: 2.0 },
          { id: 'foiling', name: 'Kurşun Çıtaların Döşenmesi & Gerdirme', hours: 3.5 },
          { id: 'soldering', name: 'Tüm Kesişim Noktalarının Lehimlenmesi', hours: 2.5 },
          { id: 'finishing', name: 'Çimentolama, Macun Temizliği & Patina', hours: 3.0 },
          { id: 'framing', name: 'Çinko Dış Kasa & Rüzgar Destek Çubukları', hours: 1.5 },
        ],
      },
      equipment: INITIAL_EQUIPMENT_LIST.map(e => ({
        ...e,
        usageHours: e.id === 'eq-grinder' ? 2.0 : e.id === 'eq-soldering-iron' ? 2.5 : 3.0,
      })),
      electricity: {
        unitRatePerKwh: 3.4,
        customElectricalEquipment: [],
      },
      marginRisk: {
        wasteRiskPercentage: 12,
        wasteCalculationMode: 'glass_and_consumables',
        targetProfitMarginPercentage: 50,
        vatTaxPercentage: 20,
        discountPercentage: 0,
      },
      breakdown: {} as any,
    },
  },
  {
    id: 'template-terrarium',
    nameTr: 'Geometrik Cam Teraryum (İkozahedron)',
    nameEn: 'Geometric Glass Terrarium (Icosahedron)',
    descriptionTr: '3D fasetli prizma cam teraryum, su sızdırmaz lehimleme.',
    descriptionEn: '3D faceted geometric prism glass terrarium with watertight seams.',
    category: 'terrarium',
    badge: '30 Üçgen Parça / ~8 Saat',
    iconName: 'Box',
    templateData: {
      metadata: {
        id: 'template-terrarium-data',
        title: '20 Yüzlü Geometrik Bitki Teraryumu (22x22cm)',
        clientName: 'Atölye Stoğu',
        projectType: 'copper_foil_3d',
        dimensions: { widthCm: 22, heightCm: 22, depthCm: 22 },
        pieceCount: 30,
        difficulty: 'intermediate',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        status: 'draft',
        notes: '2mm Ultra Clear float cam, 3D açı kalıbında montaj, bakır patina.',
      },
      glassItems: [
        {
          id: 'gt-1',
          name: '2mm Ultra Clear Düz Cam',
          type: 'Optiwhite Clear Float',
          color: 'Ultra Şeffaf',
          colorHex: '#ffffff',
          shape: 'rect',
          widthCm: 50,
          heightCm: 40,
          diameterCm: 0,
          customAreaSqCm: 2000,
          quantity: 1,
          unitPrice: 1200,
          priceUnit: 'sqm',
          calculatedAreaSqM: 0.2,
          calculatedCost: 240,
          notes: '30 adet eşkenar üçgen parça',
        },
        {
          id: 'gt-2',
          name: 'Aynalı Taban Parçası (Mirror Base)',
          type: 'Flotal Silver Mirror',
          color: 'Gümüş Ayna',
          colorHex: '#cbd5e1',
          shape: 'rect',
          widthCm: 18,
          heightCm: 18,
          diameterCm: 0,
          customAreaSqCm: 324,
          quantity: 1,
          unitPrice: 1600,
          priceUnit: 'sqm',
          calculatedAreaSqM: 0.0324,
          calculatedCost: 51.84,
          notes: 'Taban yansıtma aynası',
        },
      ],
      consumables: {
        foil: {
          enabled: true,
          foilType: 'Copper Backed',
          foilWidth: '7/32" (5.5mm)',
          lengthMeters: 14,
          rollPrice: 280,
          rollLengthMeters: 33,
        },
        solder: {
          enabled: true,
          solderRatio: '60/40',
          weightGrams: 320,
          spoolPrice: 850,
          spoolWeightGrams: 500,
        },
        chemicals: {
          fluxCost: 30,
          patinaType: 'copper',
          patinaCost: 45,
          finishingPolishCost: 30,
          cleaningSolventCost: 25,
        },
        reinforcement: {
          zincCameMeters: 0,
          zincCamePricePerMeter: 0,
          brassRodsCost: 0,
          hangingHooksCount: 0,
          hangingHookPrice: 0,
          chainMeters: 0,
          chainPricePerMeter: 0,
        },
        customConsumables: [
          { id: 't-1', name: 'Su Yalıtım Silikonu / Vernik', quantity: 1, unitCost: 40, unit: 'pcs' },
        ],
      },
      labor: {
        hourlyRate: 350,
        stages: [
          { id: 'design', name: 'Açı Şablonu & Geometri Ayarı', hours: 1.0 },
          { id: 'cutting', name: '30 Adet Hassas Üçgen Cam Kesimi', hours: 2.0 },
          { id: 'grinding', name: 'Açılı Kenar Taşlama (45 Derece Eğim)', hours: 1.5 },
          { id: 'foiling', name: 'Bakır Folyolama', hours: 1.5 },
          { id: 'soldering', name: '3D Açı Sabitleme & İç/Dış Dikiş Lehim', hours: 2.5 },
          { id: 'finishing', name: 'Bakır Patina, Nötralize Yıkama & Cila', hours: 1.0 },
        ],
      },
      equipment: INITIAL_EQUIPMENT_LIST.map(e => ({
        ...e,
        usageHours: e.id === 'eq-grinder' ? 1.5 : e.id === 'eq-soldering-iron' ? 2.5 : 1.0,
      })),
      electricity: {
        unitRatePerKwh: 3.4,
        customElectricalEquipment: [],
      },
      marginRisk: {
        wasteRiskPercentage: 10,
        wasteCalculationMode: 'glass_and_consumables',
        targetProfitMarginPercentage: 45,
        vatTaxPercentage: 20,
        discountPercentage: 0,
      },
      breakdown: {} as any,
    },
  },
];
